I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 541, in script
    "{i}%e(e)s but honteusement avant de tirer une carte pour me poser une question.{\i}"
TypeError: must be real number, not TagQuotingDict

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 541, in script
    "{i}%e(e)s but honteusement avant de tirer une carte pour me poser une question.{\i}"
  File "C:\Users\laure\Desktop\utilitaires\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\laure\Desktop\utilitaires\renpy-8.2.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\laure\Desktop\utilitaires\renpy-8.2.1-sdk\renpy\exports.py", line 1482, in say
    what = what % tag_quoting_dict
TypeError: must be real number, not TagQuotingDict

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Answer carefully 1.0
Sun Jun 16 19:25:27 2024
